### ISSUE TITLE
Unchanged equal to untranslated?

### ISSUE THREAD

**Issue by ot2sen** [joomla-projects/com_localise#264]
Is a save unchanged strings an option?

Looks like there could be a problem in allowing to use a string exactly similar to the source string, when unchanged is considered untranslated by com_localise.
How to make a file 100% complete when there are one or more lines in a file than is similar to the source string? Can be numbers, single Words en-GB used in other languages and names of tech items.

![localise_unchanged](https://cloud.githubusercontent.com/assets/790445/6026279/d21383c6-abd9-11e4-9d94-e7c0fc899cc3.png)

**Comment by brianteeman** [comment]
I noticed this in other systems and they make you copy the string even if
it doesn't need to be translated.

Technically it does need to be translated though as the end user might have
removed the core en-GB language files and without it their will be nothing
to load. (Or am I completely wrong)

On 3 February 2015 at 18:21, ot2sen notifications@github.com wrote:

> Is a save unchanged strings an option?
> 
> Looks like there could be a problem in allowing to use a string exactly
> similar to the source string, when unchanged is considered untranslated by
> com_localise.
> How to make a file 100% complete when there are one or more lines in a
> file than is similar to the source string? Can be numbers, single Words
> en-GB used in other languages and names of tech items.
> 
> [image: localise_unchanged]
> https://cloud.githubusercontent.com/assets/790445/6026279/d21383c6-abd9-11e4-9d94-e7c0fc899cc3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/com_localise/issues/264.

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Since 3.2/3.3 (can't remember which - this commit anyhow
https://github.com/joomla/joomla-cms/commit/2e82d6904a68e834fec9ac2cd91bcfb07b16dd2b
) we always load the en-GB file before the translations (when language
debug is off). So it's not end of the world if the string is missing
because the english one will show. But I would consider it 'good practice'
for the string to exist anyway.

**Comment by brianteeman** [comment]
Yes but the user can uninstall en-GB

**Comment by ot2sen** [comment]
Yes, it is the lack of option to save an unchanged string that is the issue.
Other systems will allow you to save/approve the translated string individually nomatter if it is a 100% match of the source string.

Often there are perfect matches and it cannot be considered untranslated when items are actually the same in the target language.

**Comment by infograf768** [comment]
When one completes a translation in his/her language (including unchanged strings), it can be marked as "Complete" in the "Details" tab <b>and then saved</b>, it will therefore show as "Translated" in the Manager and unchanged strings in the Phrases column show as (205 + 10)/215 where 10 is the number of unchanged strings.
[If we have an untranslated string (string absent from the target language), the background is not orange but reddish).]
![screen shot 2015-02-04 at 09 57 16](https://cloud.githubusercontent.com/assets/869724/6037482/4f772dfc-ac54-11e4-9089-a53801d5af57.png)

Example

![screen shot 2015-02-04 at 09 56 06](https://cloud.githubusercontent.com/assets/869724/6037462/1751c1bc-ac54-11e4-894d-24e25677f08e.png)

Example:

![screen shot 2015-02-04 at 08 42 34](https://cloud.githubusercontent.com/assets/869724/6036727/d9c2475e-ac49-11e4-9270-84ba0bce55e1.png)

![screen shot 2015-02-04 at 08 45 47](https://cloud.githubusercontent.com/assets/869724/6036749/4129f612-ac4a-11e4-9020-b6227254614a.png)

Same as your screenshot above:
![screen shot 2015-02-04 at 08 46 44](https://cloud.githubusercontent.com/assets/869724/6036764/6d62daa0-ac4a-11e4-8c1d-25b7bdf58fab.png)

A notable improvement is proposed by Valc here:
https://github.com/joomla-projects/com_localise/pull/259

It works, but what would make it even easier is a box near the string which would enter in db the status of the string as a special key when ticked.

Would be something like this:
![unchnanged](https://cloud.githubusercontent.com/assets/869724/6036846/cf95d01e-ac4b-11e4-88f0-9f3f512db068.jpg)

**Comment by infograf768** [comment]
FYI, en-GB can't be deleted (normally) as it is protected.
![screen shot 2015-02-04 at 10 00 54](https://cloud.githubusercontent.com/assets/869724/6037526/c0349d90-ac54-11e4-82ab-218c1c12e1aa.png)

Also, the reference language can be changed (bug corrected in 4.0.10-dev). For example fr-CA could use fr-FR as reference and customise in function of canadian French usage.

**Comment by ot2sen** [comment]
Thanks @infograf768  the details tick complete option was good to know.
Agree it would be useful to have such a tick box directly next to the individual strings.

**Comment by Valc** [comment]
Hi :)
For me unchanged means "maybe translated or maybe not translated" and is required open the file to take a look about what means in each key case.

Maybe the user have no time to translate the file with one attempt and that ones are also counted as unchanged, for example.

With the "complete" checkbox is a bit the same: what happens when new keys are present in source due the next Joomla! update have keys to add and have required translation?

But in this moment all this one is usefull due there are a way than try to help there.

I think that with only the status translated or untranslated is more easy to know what files have required to be opened due really have keys to translate, and we are talking about close to 300 languages files and a good amount of special strings cases.

My pull is focused to resolve that one and then the really pending to translate will be showed, and the user can to see in easy way what files edit (and also helps with other types of special strings)

For sure that i like much more have a tick box close to the key but i was not able to start programming in that level within Joomla, so, that pull was the result doing my best: I am not a pro, for me is a hobby.

That tick box can to be used within "Default" section types to choise between translated or untranslated state and within the section "Keys to keep as extra" or "Keys to delete" to populate the state between both (at the begin, all the now called "extra keys" should be called  "keys to delete")

With protected keys, maybe is not wrong at all use the new tab in "options" such as in my pull due have required know in deep what should be "read only" keys.

ADDED:
About "keys to add or keys to delete" i think that also is good to have a way than allow set this state only for users than know about what are handling, but is very usefull than they can to found the tick box there.

Maybe the same for protected keys if not added from the new options tab but to much ticks boxes very close maybe is not the best.

Regards.

**Comment by infograf768** [comment]
> With the "complete" checkbox is a bit the same: what happens when new keys are present in source due the next Joomla! update have keys to add and have required translation?

This is a bug. It was working in the past: We should get in this case a bar containing some red instead of the tick box in the Translated column. Example;
![screen shot 2015-02-06 at 08 20 29](https://cloud.githubusercontent.com/assets/869724/6075751/31d8f3d0-add9-11e4-9c89-ae395c643e6d.png)

We may solve this by changing here:
https://github.com/joomla-projects/com_localise/blob/develop/component/admin/views/translations/tmpl/default_body.php#L106
`<?php elseif ($item->translated == $item->total || $item->complete) : ?>`
to
`<?php elseif (($item->translated + $item->unchanged) == $item->total && $item->complete) : ?>`

**Comment by infograf768** [comment]
I am now commiting that change as well as some changes in the translations model as 4 plugins are unnecessary as they were not finally merged into 3.4.0 + com_weblinks.ini (site) was not considered as present in reference language and should for now.

**Comment by infograf768** [comment]
See https://github.com/joomla-projects/com_localise/commit/c25c3666a2db245a26d4a592c78001c92f621f82
